### PR TITLE
Add CameraView

### PR DESCRIPTION
**Pull request by jfversluis**
## What changes to the docs does this PR provide?

Very basic docs and description of the members of `CameraView`

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[f7636bb](https://github.com/jfversluis/xamarin-communitytoolkit/commits/f7636bb8f1bd1676429ebb61d4f4571ac4ca1f07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/cameraview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/views/cameraview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) | [Details](#user-content-2493b943-f8f53bfe)
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) |

<a id="2493b943-f8f53bfe"></a>
### [docs/views/cameraview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/views/cameraview.md)
 - **Line 46, Column 20**: **[Warning-xref-not-found]** `````Cross reference not found: 'Xamarin.Forms.ICommand'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012011942542792-32%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CdOsxjCvs5lQAE1Rwk6eQ2a8JwLXsVXIUDA6zUGZBnk%3D&st=2020-12-01T19%3A38%3A35Z&se=2021-01-01T19%3A43%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[e8bfd0e](https://github.com/jfversluis/xamarin-communitytoolkit/commits/e8bfd0e6ce4462552bdf00b35946a3970471acc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) |
[docs/views/cameraview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/views/cameraview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012011947146850-32%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qdh6ioetkh4c8iPZhQLLbbpffoFTd%2Bcmt9AQKyIOiZs%3D&st=2020-12-01T19%3A42%3A54Z&se=2021-01-01T19%3A47%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @jfversluis

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[e55ca8a](https://github.com/jfversluis/xamarin-communitytoolkit/commits/e55ca8a7e5a7330f6792ce1ceba4e4fadaff6556)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) |
[docs/views/cameraview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/cameraview/docs/views/cameraview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/cameraview?branch=pr-en-us-32) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071022170820-32%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UuwOV6SBQ8FP3XNpZauRptc4nfRlqSppC8rOOFsjgGs%3D&st=2020-12-07T10%3A18%3A02Z&se=2021-01-07T10%3A23%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
