### PR TITLE
Add TabView & minor fixes

### PR DESCRIPTION
**Pull request by jfversluis**
## What changes to the docs does this PR provide?

Adds basic Docs for `TabView` and minor fixes in other pages

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[6ec1d30](https://github.com/jfversluis/xamarin-communitytoolkit/commits/6ec1d303e77520001d458d959aa511ff7d0e1d42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/statelayout.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/statelayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/tabview?branch=pr-en-us-46) |
[docs/views/uniformgrid.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/uniformgrid?branch=pr-en-us-46) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012171906057654-46%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dpf6Wi4lJvJ5VoXqRLmfdGRZfjtWsraAVfErk2gEH6U%3D&st=2020-12-17T19%3A01%3A42Z&se=2021-01-17T19%3A06%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[e45dce4](https://github.com/jfversluis/xamarin-communitytoolkit/commits/e45dce4dee501cb41809d187aa9c86e00535d8b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/tabview?branch=pr-en-us-46) | [Details](#user-content-62f08799-d75d9dd4)
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/statelayout.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/statelayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/uniformgrid.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/uniformgrid?branch=pr-en-us-46) |

<a id="62f08799-d75d9dd4"></a>
### [docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md)
 - **Line 102, Column 14**: **[Warning-xref-not-found]** `````Cross reference not found: 'Xamarin.Forms.FontSize'.`````
 - **Line 103, Column 22**: **[Warning-xref-not-found]** `````Cross reference not found: 'Xamarin.Forms.FontSize'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012171919144276-46%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oTkyz8ORyO6WCyvGF0aBTehL0gcOimTbsdGa9PB3PuM%3D&st=2020-12-17T19%3A14%3A59Z&se=2021-01-17T19%3A19%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[66a3c99](https://github.com/jfversluis/xamarin-communitytoolkit/commits/66a3c995b1bbaac7085187fc1ab3a6eaf18a7fdb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/statelayout.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/statelayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/tabview?branch=pr-en-us-46) |
[docs/views/uniformgrid.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/uniformgrid?branch=pr-en-us-46) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012171949352499-46%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7Qt1%2B%2BzHpVM22nNGV1TxjGbRggQKBzAefNvc7k2ej8Q%3D&st=2020-12-17T19%3A45%3A21Z&se=2021-01-17T19%3A50%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[7553538](https://github.com/jfversluis/xamarin-communitytoolkit/commits/7553538a5c8e18d360b646868340b2a23e57cf6a)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Review by davidbritch — CHANGES_REQUESTED** [review]
TabIndicatorPlacement needs a description.

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[7553538](https://github.com/jfversluis/xamarin-communitytoolkit/commits/7553538a5c8e18d360b646868340b2a23e57cf6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/statelayout.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/statelayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/tabview?branch=pr-en-us-46) |
[docs/views/uniformgrid.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/uniformgrid?branch=pr-en-us-46) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012181005292641-46%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wvINnmJtCtVhEsANn%2BfpYPRrzoGGIrxyJn5huHEgyQU%3D&st=2020-12-18T10%3A01%3A16Z&se=2021-01-18T10%3A06%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[1f2dbc7](https://github.com/jfversluis/xamarin-communitytoolkit/commits/1f2dbc70f24d5a595bbdea199774ebe53ac3b3c3)_: 

:clock10: **Pending**: waiting for processors ([25](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 25 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[1f2dbc7](https://github.com/jfversluis/xamarin-communitytoolkit/commits/1f2dbc70f24d5a595bbdea199774ebe53ac3b3c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/statelayout.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/statelayout.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/statelayout?branch=pr-en-us-46) |
[docs/views/tabview.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/tabview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/tabview?branch=pr-en-us-46) |
[docs/views/uniformgrid.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/add-tabview/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views/uniformgrid?branch=pr-en-us-46) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012181906379533-46%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p1B5xJov9O8VMllaiy06HCD9k5UVk9ASScxbDwzUrSQ%3D&st=2020-12-18T19%3A02%3A22Z&se=2021-01-18T19%3A07%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Done!

**Review by davidbritch — APPROVED** [review]
Thanks @jfversluis

**Pull request merged**
