### PR TITLE
Added visual states section

### LINKED ISSUE #92: To be added: ValidationBehavior VisualStates
https://github.com/xamarin/XamarinCommunityToolkit/pull/955 need to be added.

### PR DESCRIPTION
**Pull request by Cfun1**
## What changes to the docs does this PR provide?

Added visual states section with a sample of usage.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [ ] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

## Other information

it is available only in version v1.1.0-pre2 yet, will be available on next stable release.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[109f745](https://github.com/Cfun1/xamarin-communitytoolkit/commits/109f745b7153291fbaac22e2d7990b5cdd55b691)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/validationbehavior?branch=pr-en-us-99) | [Details](#user-content-3eb8adc8-1b75425a)

<a id="3eb8adc8-1b75425a"></a>
### [docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md)
 - **Line 27, Column 102**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103121721293677-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rA4NcEbmAWR5JGdDwvTe4oj4YpgdaNRkoscdfRBbu6k%3D&st=2021-03-12T17%3A17%3A06Z&se=2021-04-12T17%3A22%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[a5d4cc9](https://github.com/Cfun1/xamarin-communitytoolkit/commits/a5d4cc91a47617cb40db59d56722d70626e7f830)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/validationbehavior?branch=pr-en-us-99) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103121724276739-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EAXJ8cbUrj0ejsLdxJKFmjlTDu2xkAwy%2BuvO31YllFg%3D&st=2021-03-12T17%3A20%3A10Z&se=2021-04-12T17%3A25%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[bb312af](https://github.com/Cfun1/xamarin-communitytoolkit/commits/bb312afa1236cadd43f353a5300bfd8c6e860a09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/validationbehavior?branch=pr-en-us-99) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103121729004455-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kbV%2BB%2BHRscqTjRWKrO6nRjTdwF5%2B5c6kHl3%2FuPM%2BKzY%3D&st=2021-03-12T17%3A24%3A43Z&se=2021-04-12T17%3A29%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[e7357cd](https://github.com/Cfun1/xamarin-communitytoolkit/commits/e7357cdb9b1063fcfeb288c2ea9e502de71f6350)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/validationbehavior?branch=pr-en-us-99) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103121732153842-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rc9VPLMeqJ7r3almyZ26Kp4kbuvHwr2N3IZoYum63%2Bw%3D&st=2021-03-12T17%3A27%3A53Z&se=2021-04-12T17%3A32%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @Cfun1

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[c087bd6](https://github.com/Cfun1/xamarin-communitytoolkit/commits/c087bd65f476a88e62c9a53c6b85a95cde33fceb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/validationbehavior.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/behaviors/validationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/behaviors/validationbehavior?branch=pr-en-us-99) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103231003474739-99%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ziw7ySuELRDYAu28DWjhgH%2BUR0NmURGISq%2FEvzLVX6k%3D&st=2021-03-23T09%3A59%3A32Z&se=2021-04-23T10%3A04%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
