### PR TITLE
Screen Shoot Fix

### PR DESCRIPTION
**Pull request by thimanshu1993**
Uniform Grid sample screen shoot.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[61fc79c](https://github.com/thimanshu1993/xamarin-communitytoolkit/commits/61fc79cf4ba73264bd380ee4f8ccc4618be34104)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/uniformgrid.md](https://github.com/thimanshu1993/xamarin-communitytoolkit/blob/patch-3/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/uniformgrid?branch=pr-en-us-147) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202203290955248678-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T09%3A56%3A16Z&sr=b&sp=r&sig=QH%2Bir3nOpd%2Fz9Me0%2FmqhsiiwXTGgWCrya3y7jd2syeM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by thimanshu1993** [comment]
Sample screen shot fix

**Review by jfversluis — CHANGES_REQUESTED** [review]
I see that the screenshot it not working now, but this isn't the right fix. We still want to show the smaller version and keep the lightbox selector so the reader can zoom in

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[43c8f01](https://github.com/thimanshu1993/xamarin-communitytoolkit/commits/43c8f015acfc6d561a473742759fa593579259ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/uniformgrid.md](https://github.com/thimanshu1993/xamarin-communitytoolkit/blob/patch-3/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/uniformgrid?branch=pr-en-us-147) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202203291121563398-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T11%3A22%3A54Z&sr=b&sp=r&sig=BJMlns5b5EBpzQIxONoSQho%2FiJz7i75BJd0FMJf2UgU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[a8fd8a3](https://github.com/thimanshu1993/xamarin-communitytoolkit/commits/a8fd8a31e29ebb3096f5fb385128768678248355)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/uniformgrid.md](https://github.com/thimanshu1993/xamarin-communitytoolkit/blob/patch-3/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/uniformgrid?branch=pr-en-us-147) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202203291128167303-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T11%3A29%3A22Z&sr=b&sp=r&sig=8l3m9pnkFwcuuZ7EgGsUg%2Bs%2FcLAnBVngssYArl7PCUo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[51cf2fd](https://github.com/thimanshu1993/xamarin-communitytoolkit/commits/51cf2fd9ef369242b3036b4d17931bfab2c0738b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/uniformgrid.md](https://github.com/thimanshu1993/xamarin-communitytoolkit/blob/patch-3/docs/views/uniformgrid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/uniformgrid?branch=pr-en-us-147) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202203291130152196-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T11%3A31%3A02Z&sr=b&sp=r&sig=JNc33aYV%2FsUrQ99kKqElz3SE4SGEsEVAMRiMN3FYw2I%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Fine, then no lightbox

**Comment by jfversluis** [comment]
Thanks for pointing this out @thimanshu1993 !

**Pull request merged**
