### PR TITLE
Update mediaelement.md

### PR DESCRIPTION
**Pull request by peterfoot**
## What changes to the docs does this PR provide?

Changed section on Position property to reflect data-binding support rather than polling
Added references to WPF implementation

## PR Checklist

Please check if your PR fulfils the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[0787e93](https://github.com/peterfoot/xamarin-communitytoolkit/commits/0787e9379f8bc43c8f869cb29f825a62f2abb409)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/mediaelement.md](https://github.com/peterfoot/xamarin-communitytoolkit/blob/patch-1/docs/views/mediaelement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/mediaelement?branch=pr-en-us-123) | [Details](#user-content-afd971d29c1a12b0253b5ee362d077ca-b6b36bbf)

<a id="afd971d29c1a12b0253b5ee362d077ca-b6b36bbf"></a>
### [docs/views/mediaelement.md](https://github.com/peterfoot/xamarin-communitytoolkit/blob/patch-1/docs/views/mediaelement.md)
 - **Line 402, Column 93**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#poll-for-position-data' in 'views/mediaelement.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105090954322298-123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mRv7D%2Bp3DSBeRrYxIwCSOyRWuLKFnGzkHPnvB5JA4fU%3D&st=2021-05-09T09%3A50%3A10Z&se=2021-06-09T09%3A55%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[6eeb202](https://github.com/peterfoot/xamarin-communitytoolkit/commits/6eeb202b84eea6908d25270d13387fecc005df69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/mediaelement.md](https://github.com/peterfoot/xamarin-communitytoolkit/blob/patch-1/docs/views/mediaelement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/mediaelement?branch=pr-en-us-123) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105091106098141-123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pNJGF8jHyLL%2Fmzunhacq19O0r%2FxLIPpVVltVgCrN7Uc%3D&st=2021-05-09T11%3A01%3A41Z&se=2021-06-09T11%3A06%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Review by davidbritch — APPROVED** [review]
Thanks @peterfoot

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[b6929f3](https://github.com/peterfoot/xamarin-communitytoolkit/commits/b6929f37137c9f73d3751cfab7fdfc4bd2ba0537)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/mediaelement.md](https://github.com/peterfoot/xamarin-communitytoolkit/blob/patch-1/docs/views/mediaelement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/mediaelement?branch=pr-en-us-123) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C10%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105101139527859-123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F%2Bud6bjSkrGRaASI5J1nzQfqU%2FhmlPpibs9LXyujKog%3D&st=2021-05-10T11%3A35%3A24Z&se=2021-06-10T11%3A40%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
