### PR TITLE
Update expander.md

### PR DESCRIPTION
**Pull request by AndreiMisiukevich**
## What changes to the docs does this PR provide?
Add description for three new properties in Expander control

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [X] Ran against a spell and grammar checker.
- [X] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[8c65f34](https://github.com/AndreiMisiukevich/xamarin-communitytoolkit/commits/8c65f34dad34ba4630dd67a2dceaa3a735b282dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/expander.md](https://github.com/AndreiMisiukevich/xamarin-communitytoolkit/blob/expander/docs/views/expander.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/expander?branch=pr-en-us-128) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106012318345203-128%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FAsUsP69EYy%2F%2BDBnhQG%2FQdFbeRUhrmM5hfe2%2FepEnTU%3D&st=2021-06-01T23%3A14%3A17Z&se=2021-07-02T23%3A19%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Change for Toolkit isn't merged yet. I think we will soon and then also release 1.2 soon after, let's sit on this for a bit until then

But thanks for adding this right away Andrei!

**Comment by AndreiMisiukevich** [comment]
@davidbritch @jfversluis can be merged now

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[5822e56](https://github.com/AndreiMisiukevich/xamarin-communitytoolkit/commits/5822e56cd7522845a32d7afb7e1c764fba960ee7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/expander.md](https://github.com/AndreiMisiukevich/xamarin-communitytoolkit/blob/expander/docs/views/expander.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/expander?branch=pr-en-us-128) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202107140920384525-128%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A25%3A02Z&ske=2021-07-20T08%3A30%3A02Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T09%3A16%3A24Z&se=2021-08-14T09%3A21%3A24Z&sr=b&sp=r&sig=%2B2E21Je33m16CffFQe1%2FoGNgWlaBmdRIR7FoxbgH%2FWk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
