### PR TITLE
Add LocalizedString Documentation

### LINKED ISSUE #84: Add LocalizedString Documentation
Documentation for [LocalizedString](https://github.com/xamarin/XamarinCommunityToolkit/blob/develop/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizedString.shared.cs).

Will be released in XCT 1.1.0

### PR DESCRIPTION
**Pull request by maxkoshevoi**
## Docs for Toolkit PR [#750](https://github.com/xamarin/XamarinCommunityToolkit/pull/750) 

This class planned to be released in 1.1, and doesn't exist in current version (1.0.2)

## What changes to the docs does this PR provide?

Added new page

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[3acf4ac](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/3acf4ac160aec21f552d16d0e7a03522ca967378)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |
[docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizedstring?branch=pr-en-us-87) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041545119077-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w7mZZJL%2BPXW2HmBiBUOTMR9spafwgq6TEA4he7xJud4%3D&st=2021-03-04T15%3A40%3A47Z&se=2021-04-04T15%3A45%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[872c407](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/872c407816ea63d043d9700f20596f5891ec59f7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2d2d8b77)

<a id="2d2d8b77"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041613127847-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zquoVNkI7NNznXvhkOshVCC53nNLVBtoG4bsnLtvQuA%3D&st=2021-03-04T16%3A08%3A24Z&se=2021-04-04T16%3A13%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[56736ca](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/56736ca9afb7b2ac0cd3e3dd2a455d3ef3bdfa67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-54ce9493)

<a id="54ce9493"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041619297172-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TpzaWlgigZZKpHpV5BKRDMImMr188eHMj%2BfWNPztAuo%3D&st=2021-03-04T16%3A14%3A42Z&se=2021-04-04T16%3A19%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[a032420](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/a032420702648458bf0e87336da06c13bfacb607)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-67a5da1d)

<a id="67a5da1d"></a>
###
 - **[Error-[CannotMergeCommit](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot merge commit a032420702648458bf0e87336da06c13bfacb607 in branch LocalizedString of repository https://github.com/maxkoshevoi/xamarin-communitytoolkit into branch master (commit ed3014ac9b82e3ad2f7d10bd24821985599907b4). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041619410416-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XU1tS4bMoPQ4W1mj3lbJjDklhpRMY2FKGVeWCDhe0aA%3D&st=2021-03-04T16%3A14%3A58Z&se=2021-04-04T16%3A19%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @maxkoshevoi

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[04ff6b3](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/04ff6b3431676dd66f092ab738db81568c1883cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizedstring?branch=pr-en-us-87) | [Details](#user-content-eef05f97-b034aeea)
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |

<a id="eef05f97-b034aeea"></a>
### [docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md)
 - **Line 13, Column 124**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````
 - **Line 65, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041622139550-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NTRsALEqOuVIcvrqF7b3bznSaYZ3r6E5DNHqlRKbAIw%3D&st=2021-03-04T16%3A18%3A00Z&se=2021-04-04T16%3A23%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by maxkoshevoi** [comment]
@davidbritch this feature is now released in 1.1.0

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[d5e5c31](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/d5e5c319db750d22b9b92580f16bbd296f543a93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizedstring?branch=pr-en-us-87) | [Details](#user-content-e9982d95bf7f0dddc98a69ac4dff4915-320c156b)
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |

<a id="e9982d95bf7f0dddc98a69ac4dff4915-320c156b"></a>
### [docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md)
 - **Line 11, Column 124**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````
 - **Line 63, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103242008115115-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PSiKyX%2FbHwIKrYoBGjsxOG39r%2BccQ%2FZh8bQ4oKRBIxo%3D&st=2021-03-24T20%3A03%3A50Z&se=2021-04-24T20%3A08%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[59eb67d](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/59eb67d4f856de7aac6d869f59e03428adb3e4b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizedstring?branch=pr-en-us-87) | [Details](#user-content-e9982d95bf7f0dddc98a69ac4dff4915-45be2d80)
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-87) |

<a id="e9982d95bf7f0dddc98a69ac4dff4915-45be2d80"></a>
### [docs/helpers/localizedstring.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizedString/docs/helpers/localizedstring.md)
 - **Line 11, Column 124**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````
 - **Line 67, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../helpers/localizationresourcemanager.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103242013253312-87%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WZAfnejkSArlW4e9DX0qI9yua0vhKBHj6uu%2BTKAga0w%3D&st=2021-03-24T20%3A09%3A06Z&se=2021-04-24T20%3A14%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
