### PR TITLE
Behaviors takeover (#5)

### PR DESCRIPTION
**Pull request by jfversluis**
## Related to #7 

Closes #5 

Couldn't rebase because I don't have access to Alex's fork so I'll do it this way :)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[443cf0c](https://github.com/jfversluis/xamarin-communitytoolkit/commits/443cf0c6e1fb0ebb1ba83e16216ec6584759ee4c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-f5c16dcb-c21c11fb)
[docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-18) | [Details](#user-content-812ba849-c21c11fb)
[docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-2014e966-c21c11fb)
[docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-eb333e3b-c21c11fb)
[docs/behaviors/validationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/validationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-18) | [Details](#user-content-3eb8adc8-c21c11fb)
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors/toc.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/toc.yml) | :white_check_mark:Succeeded | |

<a id="f5c16dcb-c21c11fb"></a>
### [docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="812ba849-c21c11fb"></a>
### [docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="2014e966-c21c11fb"></a>
### [docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="eb333e3b-c21c11fb"></a>
### [docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 37, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3eb8adc8-c21c11fb"></a>
### [docs/behaviors/validationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/validationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 39, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010091842421497-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wh%2Bqv5ujhJWTLY6QvO4ZwLN%2FA8MPmSJpreiKoRC0bdU%3D&st=2020-10-09T18%3A38%3A16Z&se=2020-11-09T18%3A43%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[03b3f1f](https://github.com/jfversluis/xamarin-communitytoolkit/commits/03b3f1fdfb2072cb66e03efe140a303a8a1e8927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-f5c16dcb-10d6f25a)
[docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-18) | [Details](#user-content-812ba849-10d6f25a)
[docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-2014e966-10d6f25a)
[docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-eb333e3b-10d6f25a)
[docs/behaviors/validationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/validationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/validationbehavior?branch=pr-en-us-18) | [Details](#user-content-3eb8adc8-10d6f25a)
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |

<a id="f5c16dcb-10d6f25a"></a>
### [docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="812ba849-10d6f25a"></a>
### [docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="2014e966-10d6f25a"></a>
### [docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="eb333e3b-10d6f25a"></a>
### [docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 38, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="3eb8adc8-10d6f25a"></a>
### [docs/behaviors/validationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/validationbehavior.md)
 - **Line 4, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '.' is duplicated in 'behaviors/emailvalidationbehavior.md(4,14)', 'behaviors/eventtocommandbehavior.md(4,14)', 'behaviors/numericvalidationbehavior.md(4,14)', 'behaviors/textvalidationbehavior.md(4,14)', 'behaviors/validationbehavior.md(4,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 40, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010091849194112-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oVkwfsSc5bSw7Jlfab7VmEOemxhiTNPYzqLyWk22CLA%3D&st=2020-10-09T18%3A44%3A52Z&se=2020-11-09T18%3A49%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexHedley** [comment]
Is the preferred TOC to have everything in the base one and use `items:` instead of a sub `TOC.yml` e.g. Behaviours?

**Comment by jfversluis** [comment]
tbh I don't know. I somewhat like the modular approach, but the way it was in the original PR gave errors in the VS tooling although it did seem to work. Did you find anything about it in the contributions docs?

This is probably also because of my limited YAML skills :D

**Comment by AlexHedley** [comment]
I don't remember seeing anything in the contributions docs, I think it's just something I've done in other projects, probably taken inspiration from the Prism docs.

**Comment by jfversluis** [comment]
I see in Docs on how to Doc (which seem to be internal) that "it depends" on how complex it is, how many files etc. for consistency I'm going to keep it like this for now, but I might change them all in a separate PR because I kind of like that grouping. Just didn't know it was possible. Thanks for the pointer!

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[fc97949](https://github.com/jfversluis/xamarin-communitytoolkit/commits/fc97949e2c85162b63eda652fd4102b1ab1274c0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) | [Details](#user-content-956af580-147a4725)
[docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-18) | [Details](#user-content-eb333e3b-147a4725)
[docs/behaviors.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-18) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-18) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-18) |

<a id="956af580-147a4725"></a>
### [docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml)
 - **Line 18, Column 13**: **[Warning-file-not-found]** `````Invalid file link: 'behaviors/validationbehavior.md'.`````

<a id="eb333e3b-147a4725"></a>
### [docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md)
 - **Line 38, Column 0**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010091910402854-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AdVVBuuchf9iFVxKBKMyPlvf%2F9upV13Cr1eHZgwr7wU%3D&st=2020-10-09T19%3A06%3A19Z&se=2020-11-09T19%3A11%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[a1ebd5d](https://github.com/jfversluis/xamarin-communitytoolkit/commits/a1ebd5d657168fad8ce7f66351c68655c9d72915)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-18) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-18) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-18) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-18) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010091914033537-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BNg%2F0LhXmGaVmYOZ35j%2FZKWnt41CBswiHvUvru88eH8%3D&st=2020-10-09T19%3A09%3A35Z&se=2020-11-09T19%3A14%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[9013b78](https://github.com/jfversluis/xamarin-communitytoolkit/commits/9013b782369b14c5a9378b605f90e1a03c0a83ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-18) |
[docs/behaviors/emailvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/emailvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/emailvalidationbehavior?branch=pr-en-us-18) |
[docs/behaviors/eventtocommandbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/eventtocommandbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/eventtocommandbehavior?branch=pr-en-us-18) |
[docs/behaviors/numericvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/numericvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/numericvalidationbehavior?branch=pr-en-us-18) |
[docs/behaviors/textvalidationbehavior.md](https://github.com/jfversluis/xamarin-communitytoolkit/blob/behaviors-takeover/docs/behaviors/textvalidationbehavior.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors/textvalidationbehavior?branch=pr-en-us-18) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C9%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010091916149811-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mviIkA%2FBF%2BGnvR7q1aXAgGFZ4rCr0o%2FqF%2FCjggOJLcE%3D&st=2020-10-09T19%3A11%3A49Z&se=2020-11-09T19%3A16%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
I'm going to be wild on Friday evening and merge this so other can take this

**Comment by AlexHedley** [comment]
Thanks for helping out.

What else is there to do on a Friday evening whilst waiting for Mads stream...

**Pull request merged**
