### PR TITLE
Add documentation for C# Markup

### PR DESCRIPTION
**Pull request by VincentH-Net**
## What changes to the docs does this PR provide?
It adds full C# Markup documentation to the Toolkit, based on:
- Existing [documentation for C# Markup in Forms](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup)
- Documentation for additional C# Markup features in [Forms PR #11428](https://github.com/xamarin/Xamarin.Forms/pull/11428)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

## Additional information
This PR assumes that the existing [documentation for C# Markup in Forms](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup) will remain available at the existing url. Developers using C# Markup in **Forms 4.6 - 4.8** need to use that documentation.

After this doc is published, it is recommended to update the old documentation with a link to this new Toolkit documentation for developers using **Forms 5**

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[cb8da8a](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/cb8da8aaa3f0a61b915f68caeb880bcdf29eadb3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) | [Details](#user-content-495132b6-bd5d3816)
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

<a id="495132b6-bd5d3816"></a>
### [docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 19, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 477, Column 52**: **[Warning-file-not-found]** `````Invalid file link: '~/xamarin-forms/platform/android/index.md'.`````
 - **Line 477, Column 124**: **[Warning-file-not-found]** `````Invalid file link: '~/xamarin-forms/platform/ios/index.md'.`````
 - **Line 477, Column 192**: **[Warning-file-not-found]** `````Invalid file link: '~/xamarin-forms/platform/windows/index.md'.`````
 - **Line 505, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Additional Functionality in Xamarin Community Toolkit') are not allowed. You can only have one top-level heading.`````
 - **Line 516, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/multibinding' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 574, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 641, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202011051156480444-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DgBnWnMiiOOFbODKcCPmTNI59srDADLKhzAWzsXZbLo%3D&st=2020-11-05T11%3A52%3A29Z&se=2020-12-06T11%3A57%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
> Line 2, Column 1: [Warning-ms-author-missing] Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.

You can put in me (`joverslu`) for this tag

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[2c87a08](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/2c87a082f69ae0d5670c41d9b4deac1b096e407d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202011051214425498-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XdflF%2FbNUJahNKl3PZ31K9ZMDfq%2FMvibcYmI9npoh%2BQ%3D&st=2020-11-05T12%3A10%3A25Z&se=2020-12-06T12%3A15%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VincentH-Net** [comment]
@jfversluis can you give me access to the preview URLs? (account dev@vincenth.net) Thx

**Comment by jfversluis** [comment]
Unfortunately I cannot :( 

Just so you can review it for a bit, I made it available [here](https://1drv.ms/u/s!Anrk6U9nRknzg6Ew8sm1RaA8t_jW0w?e=i7LKyw)

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[68fe0de](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/68fe0de991a99b364ed61e19bc280e3da94ff02e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202011051553562289-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RrBvsva6bEG351HGz7WnNdaQdWm039d2aew%2BCs9E%2Br8%3D&st=2020-11-05T15%3A49%3A40Z&se=2020-12-06T15%3A54%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VincentH-Net** [comment]
> Unfortunately I cannot :(
> 
> Just so you can review it for a bit, I made it available [here](https://1drv.ms/u/s!Anrk6U9nRknzg6Ew8sm1RaA8t_jW0w?e=i7LKyw)

@jfversluis thanks; that helped to make a few small improvements. 

I'm all done now with markup and markup doc PR's. I will have time next week to process any review comments, if needed.

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[4c1eeff](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/4c1eeff9a4053ae174aa957023dac8c79676b5f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071041331269-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YI%2Fm4xoeIF4zRQHWNkxr8Z8mCbzgrecf4Xo90gt6tYY%3D&st=2020-12-07T10%3A37%3A18Z&se=2021-01-07T10%3A42%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[7d0e45d](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/7d0e45d1fffcbd54dd21df5da9c32ecc8480f374)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071042221539-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hps9S32gMNe0lQdtPPLObJT4Qo82Lcgz6bSl0%2BkMRj8%3D&st=2020-12-07T10%3A38%3A03Z&se=2021-01-07T10%3A43%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @VincentH-Net

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[f8e7036](https://github.com/VincentH-Net/xamarin-communitytoolkit/commits/f8e7036bd78a4b7b3d3163a377e2850d71b08d65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/index.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-29) |
[docs/markup.md](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/markup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |
[docs/media/shared/download.png](https://github.com/VincentH-Net/xamarin-communitytoolkit/blob/master/docs/media/shared/download.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/markup?branch=pr-en-us-29) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202012071226236201-29%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B%2BUenVMt9wlC%2FIPHen75l5L7lZImT6sIxKQdKr09mjw%3D&st=2020-12-07T12%3A22%3A09Z&se=2021-01-07T12%3A27%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
