### PR TITLE
Initial draft of toast/snackbar documentation

### LINKED ISSUE #12: Document all current Views
Write Docs for all the controls currently available. You can find these [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Views). This might be too big to pick it up in one PR, by one person since the views might be quite extensive. Feel free to add a separate issue for a certain view and link it to this one.

I think personally I would rename this in the TOC to "User Interface" to also match the Forms Docs better.

- [x] AvatarView #19
- [x] CameraView #32
- [x] Expander (can be taken from [current Forms Docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/expander)) #14
- [ ] GravatarImageSource (note; this one is also in #9, might overlap, see where it fits best)
- [x] MediaElement (can be taken from [current Forms Docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/mediaelement)) #23
- [x] RangeSlider #39 
- [ ] [SideMenuView](https://github.com/xamarin/XamarinCommunityToolkit/pull/187)
- [ ] [SnackBar](https://github.com/xamarin/XamarinCommunityToolkit/pull/261)
- [x] [Shield](https://github.com/xamarin/XamarinCommunityToolkit/pull/338) #42
- [x] [BadgeView](https://github.com/xamarin/XamarinCommunityToolkit/pull/337/) #41 
- [x] [StateLayout](https://github.com/xamarin/XamarinCommunityToolkit/pull/450) #28 
- [x] [TabView](https://github.com/xamarin/XamarinCommunityToolkit/pull/525) #46
- [x] [DockLayout](https://github.com/xamarin/XamarinCommunityToolkit/pull/432) #43 
- [x] [UniformGrid](https://github.com/xamarin/XamarinCommunityToolkit/pull/619) #44
- [x] [LazyView](https://github.com/xamarin/XamarinCommunityToolkit/pull/796) #78 
- [ ] [Popups](https://github.com/xamarin/XamarinCommunityToolkit/pull/653)

### PR DESCRIPTION
**Pull request by bijington**
## Fixes #12 

Note this is an extension of #116

## What changes to the docs does this PR provide?

Adds details on `Toast` and `Snackbar` display via `VisualElementExtensions`.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[6e837c4](https://github.com/bijington/xamarin-communitytoolkit/commits/6e837c45b1d6ec2545b217676849256e75f00d35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/toast-snackbar.md](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) | [Details](#user-content-68b2c4ed5d709ba8fa14ddc95f88a731-e7773d90)
[docs/views/toast-snackbar-images/snackbar1.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/snackbar2.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/toast-is-ready.gif](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/toast-is-ready.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/toast-is-ready.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/toast-is-ready.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |

<a id="68b2c4ed5d709ba8fa14ddc95f88a731-e7773d90"></a>
### [docs/views/toast-snackbar.md](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar.md)
 - **Line 22, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 38, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Toast is ready' is duplicated. Within an article, alt text must be unique.`````
 - **Line 66, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Toast is ready' is duplicated. Within an article, alt text must be unique.`````
 - **Line 81, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202202072204502681-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T22%3A05%3A48Z&sr=b&sp=r&sig=aDK%2BqzAEwDWXDH%2F0p2PCDH2iIbloJeopW4buW%2BnhYLw%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[c396a80](https://github.com/bijington/xamarin-communitytoolkit/commits/c396a809aa5c3e7391b0198a4ef77756e2e95e3c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/toast-snackbar.md](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) | [Details](#user-content-68b2c4ed5d709ba8fa14ddc95f88a731-603916f3)
[docs/TOC.yml](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/snackbar1.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/snackbar2.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/toast-is-ready.gif](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/toast-is-ready.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |
[docs/views/toast-snackbar-images/toast-is-ready.png](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar-images/toast-is-ready.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-144) |

<a id="68b2c4ed5d709ba8fa14ddc95f88a731-603916f3"></a>
### [docs/views/toast-snackbar.md](https://github.com/bijington/xamarin-communitytoolkit/blob/toast-snackbar/docs/views/toast-snackbar.md)
 - **Line 22, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````
 - **Line 38, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Toast is ready' is duplicated. Within an article, alt text must be unique.`````
 - **Line 66, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Toast is ready' is duplicated. Within an article, alt text must be unique.`````
 - **Line 81, Column 1**: **[Warning: table-syntax-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202202072206519375-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-10T22%3A07%3A47Z&sr=b&sp=r&sig=V5bhf%2BaGccW937dYYapYY8ZjkmM2dvF3%2FocnkTiy%2BJ0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bijington** [comment]
I need to rework the Snackbar images

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).

**Pull request closed without merging**
