### PR TITLE
EnumToIntConverter documentation

### PR DESCRIPTION
**Pull request by StepKie**
## What changes to the docs does this PR provide?

Documentation for EnumToIntConverter

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[47b051d](https://github.com/Hottemax/xamarin-communitytoolkit/commits/47b051dedde13c478f10a75220aa51159926c106)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) | [Details](#user-content-d88277d43ff6a19212fb831da6b094e9-aa156f58)
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

<a id="d88277d43ff6a19212fb831da6b094e9-aa156f58"></a>
### [docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md)
 - **Line 12, Column 129**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 15, Column 60**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker.selectedindex' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 12, Column 129**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 60**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker.selectedindex' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105201117138032-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HOyhP5pJMZZXeNjTeC9M0Q7g0c4lQ7nNM2CxWjJVrFs%3D&st=2021-05-20T11%3A12%3A51Z&se=2021-06-20T11%3A17%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[71d5eeb](https://github.com/Hottemax/xamarin-communitytoolkit/commits/71d5eebe5b6413fa9c667a7c625dd86dfe201f8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) | [Details](#user-content-d88277d43ff6a19212fb831da6b094e9-2cdc2215)
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

<a id="d88277d43ff6a19212fb831da6b094e9-2cdc2215"></a>
### [docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md)
 - **Line 12, Column 129**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/dotnet/api/xamarin.forms.picker' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 15, Column 60**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/dotnet/api/xamarin.forms.picker.selectedindex' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105201249214060-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H1detdQgxucy93rRxzylhUmBrPD448Z7U0DQyb674wc%3D&st=2021-05-20T12%3A44%3A59Z&se=2021-06-20T12%3A49%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[eddd11b](https://github.com/Hottemax/xamarin-communitytoolkit/commits/eddd11ba70f506fd9ab541579181f42ec4638ce9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) | [Details](#user-content-d88277d43ff6a19212fb831da6b094e9-25df5da0)
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

<a id="d88277d43ff6a19212fb831da6b094e9-25df5da0"></a>
### [docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md)
 - **Line 0, Column 0**: **[Suggestion-disallowed-domain]** `````Url 'xreF:Xamarin.Forms.Picker.SelectedIndex' references a disallowed domain 'xref:'. This poses a security risk.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105201410570367-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qeWK7xlYURS%2FXNKHH58Wcvz3TUtMCoKWqzWud6L%2Fti8%3D&st=2021-05-20T14%3A06%3A32Z&se=2021-06-20T14%3A11%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[94383e5](https://github.com/Hottemax/xamarin-communitytoolkit/commits/94383e57b20f793fe89218311b8aa9808d74b3fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) | [Details](#user-content-d88277d43ff6a19212fb831da6b094e9-0243dbbe)
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

<a id="d88277d43ff6a19212fb831da6b094e9-0243dbbe"></a>
### [docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md)
 - **Line 0, Column 0**: **[Suggestion-disallowed-domain]** `````Url 'xreF:Xamarin.Forms.Picker.SelectedIndex' references a disallowed domain 'xref:'. This poses a security risk.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105210917303297-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JEJfBmfmYQkqHsj0DhX7SmxkFW5rRWal6yeoYC8ONSY%3D&st=2021-05-21T09%3A13%3A03Z&se=2021-06-21T09%3A18%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[544940d](https://github.com/Hottemax/xamarin-communitytoolkit/commits/544940db7c04a0be96c02c64e11e42395da48fe0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105210919043682-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0bM86ilwKQRCyBKz1nZxftznECObQExT6UTmyPGULbw%3D&st=2021-05-21T09%3A14%3A41Z&se=2021-06-21T09%3A19%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[9b22cb4](https://github.com/Hottemax/xamarin-communitytoolkit/commits/9b22cb4771004427a0927e5838e58b32248dfb99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105211010325790-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mzoWNQzDmJOJTReFDjSN0VleBBeD%2BSZCX1NJQh1ov7I%3D&st=2021-05-21T10%3A06%3A07Z&se=2021-06-21T10%3A11%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[837078f](https://github.com/Hottemax/xamarin-communitytoolkit/commits/837078fffec3579b0277c945f5e5cf601afc8594)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |
[docs/converters/enumtointconverter.md](https://github.com/Hottemax/xamarin-communitytoolkit/blob/121-Document-EnumToIntConverter/docs/converters/enumtointconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtointconverter?branch=pr-en-us-126) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105211303187686-126%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mh2J%2BC1nxbD2RNW3iJ8WKmWCrngBG3LWtVGuFNCx1Rk%3D&st=2021-05-21T12%3A58%3A54Z&se=2021-06-21T13%3A03%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
