### PR TITLE
DocuTune: Apply metadata properties for advocate contributors

### PR DESCRIPTION
**Pull request by alexbuckgit**
DocuTune: Apply metadata properties for advocate contributors

Note the following:

- DocuTune drives improved quality of technical content by finding and automatically correcting a broad set of issues in Markdown and YAML files. DocuTune performs these updates intelligently, only making corrections in the sections of a document where the correction is suitable.
- DocuTune PRs often standardize spacing, formatting, and casing of Markdown elements to support the DocuTune onboarding process.
- DocuTune PRs might contain other minor edits noticed during a manual review.
- DocuTune PRs might include files whose Acrolinx score was below the target threshold prior to this PR.
- Delimiters such as asterisks and backticks may be added to link descriptions or alt-text to denote UI elements or other string literals that should not be modified during automation.
- Other formatting or indentation corrections might appear in DocuTune PRs to improve the accuracy of document parsing.

PointOfContact: @scottboc (Scott Bockheim)
CorrelationId: 70d29a1f-52c7-4693-b6b6-48364523765f

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[222cc27](https://github.com/alexbuckgit/xamarin-communitytoolkit/commits/222cc275c925beada056ef5669ac403ddf873be8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/delegateweakeventmanager.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/helpers/delegateweakeventmanager.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/delegateweakeventmanager?branch=pr-en-us-145) | [Details](#user-content-3a9a74fe35f2f6e365b0b77cded1200f-b21c2d32)
[docs/helpers/weakeventmanagert.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/helpers/weakeventmanagert.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/weakeventmanagert?branch=pr-en-us-145) | [Details](#user-content-cec3d2586c711d71ac5cf0c1f850dfa4-b21c2d32)
[docs/helpers/weakeventmanagerextensions.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/helpers/weakeventmanagerextensions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/weakeventmanagerextensions?branch=pr-en-us-145) |
[docs/objectmodel/asynccommand.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/objectmodel/asynccommand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/objectmodel/asynccommand?branch=pr-en-us-145) |
[docs/objectmodel/asyncvaluecommand.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/objectmodel/asyncvaluecommand.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/objectmodel/asyncvaluecommand?branch=pr-en-us-145) |

<a id="3a9a74fe35f2f6e365b0b77cded1200f-b21c2d32"></a>
### [docs/helpers/delegateweakeventmanager.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/helpers/delegateweakeventmanager.md)
 - **Line 86, Column 21**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'T' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="cec3d2586c711d71ac5cf0c1f850dfa4-b21c2d32"></a>
### [docs/helpers/weakeventmanagert.md](https://github.com/alexbuckgit/xamarin-communitytoolkit/blob/alexbuckgit/docutune-autopr-20220303-141945-1146998/docs/helpers/weakeventmanagert.md)
 - **Line 11, Column 46**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'TEventArgs' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C3%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202203031420004586-145%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-03T14%3A21%3A01Z&sr=b&sp=r&sig=S5UOkrSRP3bLdoYHvUozlqYCisVJs%2F%2B8%2FPSp1Fa8ZKU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by alexbuckgit** [comment]
#sign-off

**Comment by mikekinsman** [comment]
@jfversluis this is a PR that @alexbuckgit  and I have been working on to do some additional reporting on contributors.  we're not making any changes to content, just some additions to metadata.   The build validation errors above appear within the content itself, and aren't something that are a part of our changes... so we don't want to address them.  Can you merge this as is? or are there additional things we need to do?  Thanks! Feel free to track us down on teams to discuss.

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
Was wondering what was going on with this :) looks good to me, thanks!

**Pull request merged**
