### PR TITLE
Utc date time to local string converter docs

### PR DESCRIPTION
**Pull request by LeoJHarris**
https://github.com/xamarin/XamarinCommunityToolkit/pull/1555

New documentation added

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[aa6ea60](https://github.com/LeoJHarris/xamarin-communitytoolkit/commits/aa6ea60b1121108e7443fbdb9c99947988c5ac4f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/utcdatetimetolocalstringconverter.md](https://github.com/LeoJHarris/xamarin-communitytoolkit/blob/UtcDateTimeToLocalStringConverterDocs/docs/converters/utcdatetimetolocalstringconverter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/utcdatetimetolocalstringconverter?branch=pr-en-us-134) | [Details](#user-content-16fd07c74b81befbdc311605f713b12d-9be29e86)
[docs/TOC.yml](https://github.com/LeoJHarris/xamarin-communitytoolkit/blob/UtcDateTimeToLocalStringConverterDocs/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/utcdatetimetolocalstringconverter?branch=pr-en-us-134) |

<a id="16fd07c74b81befbdc311605f713b12d-9be29e86"></a>
### [docs/converters/utcdatetimetolocalstringconverter.md](https://github.com/LeoJHarris/xamarin-communitytoolkit/blob/UtcDateTimeToLocalStringConverterDocs/docs/converters/utcdatetimetolocalstringconverter.md)
 - **Line 6, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '20/08/2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202108201207178735-134%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vxgFzI1%2F0j%2B3XMkSuNm%2FUgTji00MOFNiysoYbqnHTko%3D&st=2021-08-20T12%3A02%3A58Z&se=2021-09-20T12%3A07%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[bd11ddd](https://github.com/LeoJHarris/xamarin-communitytoolkit/commits/bd11ddd1b96a5ec149b4f0ee8b0cbe38fb9de440)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/LeoJHarris/xamarin-communitytoolkit/blob/UtcDateTimeToLocalStringConverterDocs/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/utcdatetimetolocalstringconverter?branch=pr-en-us-134) |
[docs/converters/utcdatetimetolocalstringconverter.md](https://github.com/LeoJHarris/xamarin-communitytoolkit/blob/UtcDateTimeToLocalStringConverterDocs/docs/converters/utcdatetimetolocalstringconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/utcdatetimetolocalstringconverter?branch=pr-en-us-134) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202108201232305402-134%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=6cyaWxakFNvKOkrUCxHBSFEDULN86Kky2xPFLy9yi%2F0%3D&st=2021-08-20T12%3A28%3A14Z&se=2021-09-20T12%3A33%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Merged, but not released yet

**Comment by jfversluis** [comment]
And thank you so much @LeoJHarris for providing the full package here! Appreciate it!

**Pull request closed without merging**
