### PR TITLE
Snackbar and toast

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
## Fixes #
https://github.com/MicrosoftDocs/xamarin-communitytoolkit/issues/12 

## Docs for Toolkit PR [#](https://github.com/xamarin/XamarinCommunityToolkit/pull/#) 
https://github.com/xamarin/XamarinCommunityToolkit/pull/1005

## What changes to the docs does this PR provide?

Adds VisualElementExtensions (snackbar and toast)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [ ] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[d0d1d1e](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/d0d1d1e57634130c4fbccfc8bc6aa36b18cb77b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/extensions/visualelementextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) | [Details](#user-content-5fb569a5651a5152742ce57706db81a3-42d888da)

<a id="5fb569a5651a5152742ce57706db81a3-42d888da"></a>
### [docs/extensions/visualelementextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension.md)
 - **Line 25, Column 1**: **[Warning-[alt-text-bad-value](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Toast1' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 45, Column 1**: **[Warning-[alt-text-bad-value](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Toast2' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 0, Column 0**: **[Suggestion-external-image]** `````Image 'https://vladislavantonyuk.sirv.com/vladislavantonyuk/articles/toast1.png' references an external site. This poses a security risk and external images are unavailable in some environments. Reference an image file within the repo instead.`````
 - **Line 0, Column 0**: **[Suggestion-external-image]** `````Image 'https://vladislavantonyuk.sirv.com/vladislavantonyuk/articles/toast2.png' references an external site. This poses a security risk and external images are unavailable in some environments. Reference an image file within the repo instead.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202104161301375093-116%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KUQela1CzsACTLb0eNP35XH6Kl9M839NjVeV2rL5VGg%3D&st=2021-04-16T12%3A57%3A17Z&se=2021-05-17T13%3A02%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Thanks for providing this @VladislavAntonyuk ! There are a couple of warning in here, could you fix those?

I think we can improve the text and markup here and there too, which is fine considering you're not a native speaker so don't worry about it. This is a great start!

**Comment by VladislavAntonyuk** [comment]
@jfversluis , @davidbritch could you please suggest how to fix `references an external site` for images?

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[b290a75](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/b290a753bfaa7dbc2e9b512adc82965540256eb1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/extensions/visualelementextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) | [Details](#user-content-5fb569a5651a5152742ce57706db81a3-b6ae1934)
[docs/extensions/visualelementextension-images/snackbar1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension-images/snackbar2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension-images/toast1.webp](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/toast1.webp) | :white_check_mark:Succeeded | |
[docs/extensions/visualelementextension-images/toast2.webp](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/toast2.webp) | :white_check_mark:Succeeded | |

<a id="5fb569a5651a5152742ce57706db81a3-b6ae1934"></a>
### [docs/extensions/visualelementextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension.md)
 - **Line 25, Column 1**: **[Warning-link-out-of-scope]** `````File 'extensions/visualelementextension-images/toast1.webp' referenced by link 'visualelementextension-images/toast1.webp' will not be built because it is not included in build scope.`````
 - **Line 45, Column 1**: **[Warning-link-out-of-scope]** `````File 'extensions/visualelementextension-images/toast2.webp' referenced by link 'visualelementextension-images/toast2.webp' will not be built because it is not included in build scope.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105051038141993-116%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HRmYIua89RB1aK2RZncjzP19D2kmC1o2hoENr4N8WX8%3D&st=2021-05-05T10%3A33%3A55Z&se=2021-06-05T10%3A38%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[a8adc8c](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/a8adc8cfa9633a769aa8974783a285c659dff9db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/extensions/visualelementextension-images/snackbar1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension-images/snackbar2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension-images/toast1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/toast1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension-images/toast2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension-images/toast2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |
[docs/extensions/visualelementextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/visualelementextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/visualelementextension?branch=pr-en-us-116) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202105051042365437-116%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sn1j39IV3OyHce4zFsFc9vMmAkxb1ff6fl5bDLWjv1c%3D&st=2021-05-05T10%3A38%3A09Z&se=2021-06-05T10%3A43%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
I see you fixed the images, thanks!

I notice that this is all written for the `VisualElementExtension` but isn't it in the `PageExtension`? https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/PageExtension.shared.cs

**Comment by VladislavAntonyuk** [comment]
It is now moved to https://github.com/xamarin/XamarinCommunityToolkit/blob/develop/src/CommunityToolkit/Xamarin.CommunityToolkit/Extensions/VisualElement/VisualElementExtension.shared.cs

Maybe we should wait till develop is merged to main

**Comment by VladislavAntonyuk** [comment]
@jfversluis is it ready to be merged?

**Comment by jfversluis** [comment]
Thanks for your patience! So, I would propose taking a different approach. I think people don't really care that this is a extension method, they just want to use the SnackBar/Toast. So I would opt for adding that under Views and then tell people how to use it. That means starting with the functionality in mind instead of taking the technical implementation as a starting point.

Does that make sense?

**Comment by jfversluis** [comment]
I guess we could merge this for now to have _something_ and change it for the better later :)

In that case you still need to update the toc.yml and add this file

**Comment by TheCodeTraveler** [comment]
> I guess we could merge this for now to have something and change it for the better later :)

I'd prefer not to merge the extension method if we will add it under `Views` later, because it will introduce breaking changes in a future release.

We would have to maintain the extension method, e.g. write unit tests and provide bug fixes, only then to mark it `[Obsolete]` and  eventually remove it in a future release.

**Comment by jfversluis** [comment]
> > I guess we could merge this for now to have something and change it for the better later :)
> 
> I'd prefer not to merge the extension method if we will add it under `Views` later, because it will introduce breaking changes in a future release.
> 
> We would have to maintain the extension method, e.g. write unit tests and provide bug fixes, only then to mark it `[Obsolete]` and eventually remove it in a future release.

Note that I am talking about the Docs here, not the actual functionality ;)

**Comment by TheCodeTraveler** [comment]
Ah - apologies!

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[faa26c5](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/faa26c580bcea0f16e4efb1762d6289b6d163b39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) | [Details](#user-content-14ca8d9a66ae688ad12a62caf42de4ad-14e926be)
[docs/helpers/localizationresourcemanager.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/helpers/localizationresourcemanager.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-116) | [Details](#user-content-a8286ed8efef29121733fec1b6870be0-14e926be)
[docs/helpers/localizedstring.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/helpers/localizedstring.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizedstring?branch=pr-en-us-116) | [Details](#user-content-e9982d95bf7f0dddc98a69ac4dff4915-14e926be)
[docs/extensions/translateextension.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | |
[docs/views/toast-snackbar-images/snackbar1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/snackbar2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |

<a id="14ca8d9a66ae688ad12a62caf42de4ad-14e926be"></a>
### [docs/TOC.yml](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/TOC.yml)
 - **Line 96, Column 13**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'extensions/translateextension.md'.`````

<a id="a8286ed8efef29121733fec1b6870be0-14e926be"></a>
### [docs/helpers/localizationresourcemanager.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/helpers/localizationresourcemanager.md)
 - **Line 11, Column 156**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../extensions/translateextension.md'.`````
 - **Line 69, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../extensions/translateextension.md'.`````

<a id="e9982d95bf7f0dddc98a69ac4dff4915-14e926be"></a>
### [docs/helpers/localizedstring.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/helpers/localizedstring.md)
 - **Line 68, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../extensions/translateextension.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106201100402948-116%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pi3oljpCIgiIgt5kPX6ibSXu1%2Fh%2B9RUYs2Y%2FPkRk00g%3D&st=2021-06-20T10%3A56%3A13Z&se=2021-07-21T11%3A01%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[5aa8842](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/5aa8842e0410710d7798bfb00483a07b87bdedcb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/snackbar1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/snackbar2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C20%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106201102018732-116%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WG9zpUrq%2F%2Bdc%2BYUWqhdS78VqB5l5s3DKIEuVtwcNblc%3D&st=2021-06-20T10%3A57%3A31Z&se=2021-07-21T11%3A02%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VladislavAntonyuk** [comment]
@jfversluis moved docs to Views folder, updated TOC.yml

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[38ae726](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/commits/38ae72634edbe93f77af3627142ef8292d7c473b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/snackbar1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/snackbar2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/snackbar2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast1.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar-images/toast2.png](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar-images/toast2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |
[docs/views/toast-snackbar.md](https://github.com/VladislavAntonyuk/xamarin-communitytoolkit/blob/vantonyuk/visual-element-extension/docs/views/toast-snackbar.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/toast-snackbar?branch=pr-en-us-116) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202107162012335027-116%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A51%3A15Z&ske=2021-07-23T08%3A56%3A15Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T20%3A08%3A21Z&se=2021-08-16T20%3A13%3A21Z&sr=b&sp=r&sig=cQMyo1LXPFmm1LUt4rXtVF4KDs%2F8G2HyR6JIgK40oLY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VladislavAntonyuk** [comment]
@jfversluis are there any blockers / change requests that prevent this PR from being merged?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin Community Toolkit. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI Community Toolkit is the replacement for Xamarin Community Toolkit and its documentation can be found [here](https://learn.microsoft.com/dotnet/communitytoolkit/maui/).

**Pull request closed without merging**
