### PR TITLE
Update ShieldView properties

### PR DESCRIPTION
**Pull request by Cfun1**
## What changes to the docs does this PR provide?

Update properties list.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [x] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[17ee310](https://github.com/Cfun1/xamarin-communitytoolkit/commits/17ee310c610d44cd865a665b633872e0924d44a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/shield.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/views/shield.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202102121806015643-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g2RWA%2FuDlbFZ7kYEZTZm0CbontRPdMSpmLU8WTZil%2BU%3D&st=2021-02-12T18%3A01%3A43Z&se=2021-03-15T18%3A06%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Cfun1** [comment]
@jfversluis should we mentioned the deprecated properties? if yes what is the format to follow ?

**Comment by Cfun1** [comment]
@jfversluis should we mentioned the deprecated properties? if yes what is the format to follow ?

**Comment by jfversluis** [comment]
I think that makes sense. Just add a note like: Deprecated since 1.1, use x instead and we can remove that somewhere later on when the property is removed as a whole

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[cf58a16](https://github.com/Cfun1/xamarin-communitytoolkit/commits/cf58a16903b7cc9a6733359fe395693858070197)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/shield.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/views/shield.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202102122220419091-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VzCH1kdd%2F0snidPxkKWPLvmBxBXw0o%2F4wsDyD2URXYA%3D&st=2021-02-12T22%3A16%3A17Z&se=2021-03-15T22%3A21%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[738670d](https://github.com/Cfun1/xamarin-communitytoolkit/commits/738670d7b3e57ce690ed7f9fa2caddfa554eaf3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/shield.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/views/shield.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202102150112105751-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zKcfhpZU2W7qP5FazpWxsdTkg8SrpSL496Satm1kIBo%3D&st=2021-02-15T01%3A07%3A45Z&se=2021-03-18T01%3A12%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @Cfun1

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[540b806](https://github.com/Cfun1/xamarin-communitytoolkit/commits/540b8062b78ca6a9d441b2a5e04900b911070526)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/views/shield.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-1/docs/views/shield.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/views/shield?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202102150911007878-80%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wshOKO8zZcC6lzfCgZ39p4dbgHgJZ92xusj3fbS5ZdE%3D&st=2021-02-15T09%3A06%3A39Z&se=2021-03-18T09%3A11%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
