### PR TITLE
created LifecycleEffect doc

### LINKED ISSUE #88: Added Life cycle events
Open this issue to keep track of missing docs https://github.com/xamarin/XamarinCommunityToolkit/pull/674

### PR DESCRIPTION
**Pull request by pictos**
## What changes to the docs does this PR provide?

Added the doc.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [ ] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [ ] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[0ec1e14](https://github.com/pictos/xamarin-communitytoolkit/commits/0ec1e147cd413125ad07a058a008d85f8104da89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/effects/lifecycleeffect.md](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/effects/lifecycleeffect.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) | [Details](#user-content-777ea4f61e3eb9147fa9b37e1ada3735-fae920e2)
[docs/TOC.yml](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |

<a id="777ea4f61e3eb9147fa9b37e1ada3735-fae920e2"></a>
### [docs/effects/lifecycleeffect.md](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/effects/lifecycleeffect.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'This article explains how to use LazyView, which lets you delay the initialization of a View.' is duplicated in 'effects/lifecycleeffect.md(3,14)', 'views/lazyview.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103192229069649-103%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nte1CVnkT2ZQUsE8zBomdoumi6prIzNE5vGVfePCMAg%3D&st=2021-03-19T22%3A24%3A45Z&se=2021-04-19T22%3A29%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[ea9735b](https://github.com/pictos/xamarin-communitytoolkit/commits/ea9735b842b6df59e2e4089882ca2248a35c1b41)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |
[docs/effects/lifecycleeffect.md](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/effects/lifecycleeffect.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103192239137644-103%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dbeR4tiufuGybF4esbuk0i0ioB0lRf9doZ6BkfrajpM%3D&st=2021-03-19T22%3A34%3A57Z&se=2021-04-19T22%3A39%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[29a2572](https://github.com/pictos/xamarin-communitytoolkit/commits/29a257228dcca358eb47570814b2f291a6d9d537)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |
[docs/effects/lifecycleeffect.md](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/effects/lifecycleeffect.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103220922066305-103%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cop4PuWQFYPAMbyFXyRkXcreQVuPuD1noi3SWdpuBu4%3D&st=2021-03-22T09%3A17%3A50Z&se=2021-04-22T09%3A22%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by jfversluis** [comment]
Pre-release can be removed and this can be merged!

**Review by davidbritch — APPROVED** [review]
Thanks @pictos

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[e04fb33](https://github.com/pictos/xamarin-communitytoolkit/commits/e04fb332cd7afbb220680b8699ec93cf9b7e86bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |
[docs/effects/lifecycleeffect.md](https://github.com/pictos/xamarin-communitytoolkit/blob/pj/Lifecycle-effects/docs/effects/lifecycleeffect.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/effects/lifecycleeffect?branch=pr-en-us-103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103230956422712-103%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7k%2FLmgwSkUUPDkM5O%2FZ7WhyhWepK%2BebLNMYIM4gmDNM%3D&st=2021-03-23T09%3A52%3A20Z&se=2021-04-23T09%3A57%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
