### PR TITLE
Added IsInRangeConverter documentation

### PR DESCRIPTION
**Pull request by GUOLDEV**
## Fixes # 
NA
## What changes to the docs does this PR provide?

Added IsInRangeConverter Documentation
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[4bdb56c](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/4bdb56cd8110dd81f306ccdaf49f37aecb9ae516)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) | [Details](#user-content-13a314c91f559c4817178683555dfb3c-5b339800)

<a id="13a314c91f559c4817178683555dfb3c-5b339800"></a>
### [docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md)
 - **Line 6, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '12/06/2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120312020301-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N1dZ0%2Fo3ozzC9GRRj%2FVxNRRqYQPEPdReMD%2FkJNJIcuA%3D&st=2021-06-12T03%3A07%3A31Z&se=2021-07-13T03%3A12%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[01eb41f](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/01eb41f5a98d91fb0c9697eb448105c2643c0e74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120314538947-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b1FHmlBQutccGlOdfa%2F7GUPcNU7rAjTuLGQkDt3VbXE%3D&st=2021-06-12T03%3A10%3A36Z&se=2021-07-13T03%3A15%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[180d659](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/180d6592e967ccb9ea1d173c7776adcc8e543eff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120316527579-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jEt%2BlWISAezwAmJ8F7rl6OLutqtw7d5qK%2FrkjuLOlWw%3D&st=2021-06-12T03%3A12%3A35Z&se=2021-07-13T03%3A17%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[cb3103e](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/cb3103e4f3eb4b932ae02d8705ce2cacfd9234ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120321186680-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ip1oQZTRdrgtB96NYTEUdAEBl3%2F298kUZaCYEV%2Fcd6o%3D&st=2021-06-12T03%3A17%3A01Z&se=2021-07-13T03%3A22%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[880cfd0](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/880cfd0170a264b88de3c482934d2d29e0ff7890)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120338535026-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g9KuMdlsshgv6kD5kIULomfvN54eQwH0sbtARNzx%2Biw%3D&st=2021-06-12T03%3A34%3A35Z&se=2021-07-13T03%3A39%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[b8e1de7](https://github.com/GUOLDEV/xamarin-communitytoolkit/commits/b8e1de7bf071e93c0728e2c7a9b57b03eac3b7bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |
[docs/converters/isinrangeconverter.md](https://github.com/GUOLDEV/xamarin-communitytoolkit/blob/guoldev/isinrangeconverter-doc/docs/converters/isinrangeconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/isinrangeconverter?branch=pr-en-us-130) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C12%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202106120357598204-130%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ztkf7VOc4VZa8FbYyTNN9k%2BEmu9vqcrRulpsFmV0XQA%3D&st=2021-06-12T03%3A53%3A40Z&se=2021-07-13T03%3A58%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
