### PR TITLE
Add LocalizationResourceManager Documentation (Updated to 1.1.0)

### LINKED ISSUE #83: Add LocalizationManager Documentation
@maxkoshevoi please add the documentation for [`LocalizationResourceManager`](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs)

### PR DESCRIPTION
**Pull request by maxkoshevoi**
## Fixes #83 

Closes #97 

## What changes to the docs does this PR provide?

Added new page

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[98cdc7f](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/98cdc7fd2e3e9801a7f4c854075840f52d149d5f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-105) | [Details](#user-content-a8286ed8efef29121733fec1b6870be0-7e916083)
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |

<a id="a8286ed8efef29121733fec1b6870be0-7e916083"></a>
### [docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md)
 - **Line 11, Column 224**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'localizedstring.md'.`````
 - **Line 70, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'localizedstring.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103241939577252-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=88V5e2GV3nqJuhfx%2FVNo4yJcqHbwN4SPqI2KqO6wo1Y%3D&st=2021-03-24T19%3A35%3A38Z&se=2021-04-24T19%3A40%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[441d816](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/441d816a448b11d387e4b03f7de41172a1ac0ef3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f9cb31d9)

<a id="f9cb31d9"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103241949164334-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gz1VTtoAxvYCdBdVA6m%2FOmrrjcqdyjQNyLCbQz6GKww%3D&st=2021-03-24T19%3A44%3A42Z&se=2021-04-24T19%3A49%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[0247ac4](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/0247ac44e7ffd349575448314b77c8bc5d834ebb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-105) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103241954104999-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h1mHTHQRySbxu%2FvEUBaf%2FcJbXIa%2B9kwKb%2B375SdqwAU%3D&st=2021-03-24T19%3A49%3A49Z&se=2021-04-24T19%3A54%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[36e8969](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/36e89699fc6d1a7aa1147056256105f96a1dcad8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-105) | [Details](#user-content-a8286ed8efef29121733fec1b6870be0-262e1f6f)
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |

<a id="a8286ed8efef29121733fec1b6870be0-262e1f6f"></a>
### [docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md)
 - **Line 11, Column 224**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'localizedstring.md'.`````
 - **Line 70, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'localizedstring.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103242004006402-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WjKFL15R1nzfOsHvU9qt8jU%2FxxoUZeYddshI%2FOiEaQY%3D&st=2021-03-24T19%3A59%3A38Z&se=2021-04-24T20%3A04%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[ed6f1fa](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/ed6f1fa6e42a88ecf9f5ec6a41a8eb9993e0b76c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-37a21612)

<a id="37a21612"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103251023510243-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7YfgkXAOx37nZxqsJU%2Bn5kBcmEQnK1xUyKeE%2BlRZbEc%3D&st=2021-03-25T10%3A19%3A01Z&se=2021-04-25T10%3A24%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @maxkoshevoi

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[728e552](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/728e552f66916aa4b3336e821be1fd53c15c2491)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-105) |
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/lrm-1.1.0/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-105) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103251026037461-105%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IWKS6OOX01MJ0P0AQnCu5WLqr82Ky8fgLZ6Op%2B8z4wk%3D&st=2021-03-25T10%3A21%3A42Z&se=2021-04-25T10%3A26%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
