### PR TITLE
Added CompareConverter

### PR DESCRIPTION
**Pull request by Cfun1**
## Docs for Toolkit PR [#1172](https://github.com/xamarin/XamarinCommunityToolkit/pull/1172)  
## What changes to the docs does this PR provide?

Added documentation for CompareConverter.

## PR Checklist

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [ ] Ran against a spell and grammar checker.
- [ ] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[e0eddb8](https://github.com/Cfun1/xamarin-communitytoolkit/commits/e0eddb8e872a1a08be2bdb74680924983d37291d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |
[docs/converters/compareconverter.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/converters/compareconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202104051914077628-112%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a53C5RNUgEAhrgcg3ZLv7pEULizidJjswLw%2FxonYVL8%3D&st=2021-04-05T19%3A09%3A46Z&se=2021-05-06T19%3A14%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[bde7524](https://github.com/Cfun1/xamarin-communitytoolkit/commits/bde752428ad5c064f7d86ed4fec8e4fa4731e20a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |
[docs/converters/compareconverter.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/converters/compareconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202104071113147251-112%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NGs%2BR9axrbGCuYCnQD%2B1B5K8bFeOR6KpQvxqnBf09O0%3D&st=2021-04-07T11%3A08%3A56Z&se=2021-05-08T11%3A13%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
How about mentioning valid values of `ComparisonOperator`? It'll be difficult for people to use this converter without seeing those values.

**Comment by Cfun1** [comment]
Good idea, I wanted to mention that in xaml IntelliSense will suggest the valid values since it's an eum used with the [flags] attribute, but we will add them anyway to the docs.
a

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[d717193](https://github.com/Cfun1/xamarin-communitytoolkit/commits/d71719340e2c3a371089a999f01bdd69ad1dd38b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |
[docs/converters/compareconverter.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/converters/compareconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202104071135072304-112%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q2fqkV5ZxO49FPA16coTu307U%2FXymQMs37s5sMkfPWA%3D&st=2021-04-07T11%3A30%3A47Z&se=2021-05-08T11%3A35%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by jfversluis — APPROVED** [review]

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[894289b](https://github.com/Cfun1/xamarin-communitytoolkit/commits/894289bb787b445641f660990a30456dfb3c7da7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |
[docs/converters/compareconverter.md](https://github.com/Cfun1/xamarin-communitytoolkit/blob/patch-2/docs/converters/compareconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/compareconverter?branch=pr-en-us-112) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C14%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202107141055224471-112%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A34%3A59Z&ske=2021-07-20T08%3A39%3A59Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-14T10%3A51%3A02Z&se=2021-08-14T10%3A56%3A02Z&sr=b&sp=r&sig=9et5gaYlEY0V8GKDMteegh5xyPmG4svsZ5E0qNHvQnc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
