### PR TITLE
Add LocalizationManager Documentation

### LINKED ISSUE #83: Add LocalizationManager Documentation
@maxkoshevoi please add the documentation for [`LocalizationResourceManager`](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs)

### PR DESCRIPTION
**Pull request by maxkoshevoi**
## What changes to the docs does this PR provide?

Added new page

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Review by jfversluis — APPROVED** [review]

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[704c8bb](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/704c8bb01c13afa8bd98650c46ea7e1b4e63af3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-86) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041512090395-86%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=83T0TY78VAIr3Wd1y0B289heZCLIIpxx1nvMbrTPdm4%3D&st=2021-03-04T15%3A08%3A01Z&se=2021-04-04T15%3A13%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @maxkoshevoi

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[c16f681](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/c16f681fa09778a4bef04a961201fa051efefe7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-86) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041518536661-86%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HkxXlngHOrZvWJXtwHEfdAKT5ov9OJB7hRsYA0oSrpc%3D&st=2021-03-04T15%3A14%3A33Z&se=2021-04-04T15%3A19%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[7422cf9](https://github.com/maxkoshevoi/xamarin-communitytoolkit/commits/7422cf9614bf7346120229df8f662b53a2c30219)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/extensions/translateextension.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-86) |
[docs/helpers/localizationresourcemanager.md](https://github.com/maxkoshevoi/xamarin-communitytoolkit/blob/LocalizationResourceManager/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-86) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041520482906-86%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hrtyYPR1mg8xRkkIp5QJdUtVmXCTEIxLH7Lpc3fkF8g%3D&st=2021-03-04T15%3A16%3A32Z&se=2021-04-04T15%3A21%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
