### PR TITLE
Added SafeAreaEffect, reworked general pages

### LINKED ISSUE #6: Document all current Effects
There is currently one effect, you can find it/them [here](https://github.com/xamarin/XamarinCommunityToolkit/tree/main/XamarinCommunityToolkit/Effects)

- [ ] SafeAreaEffect

### PR DESCRIPTION
**Pull request by sthewissen**
## Fixes
- Fixes #6 

## What changes to the docs does this PR provide?

- Adds Effects > SafeAreaEffect
- Reworks the general Setup / information pages
- Reworks the TOC a bit

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [X] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/toc.yml).
- [X] Ran against a spell and grammar checker.
- [X] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[d2eb637](https://github.com/sthewissen/xamarin-communitytoolkit/commits/d2eb637fa770fdf4c5e9b1fddaa3a57c7afb7272)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) | [Details](#user-content-956af580-1e5e0709)
[docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) | [Details](#user-content-b6b6e95c-1e5e0709)
[docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) | [Details](#user-content-f5f9d1df-1e5e0709)
[docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-13) | [Details](#user-content-d93b521a-1e5e0709)
[docs/views.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/views.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/views?branch=pr-en-us-13) | [Details](#user-content-36ca80ad-1e5e0709)
[docs/behaviors.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/behaviors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/behaviors?branch=pr-en-us-13) | [Details](#user-content-c6ea3cfb-1e5e0709)
[docs/converters.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/converters.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/converters?branch=pr-en-us-13) | [Details](#user-content-ca2a8b71-1e5e0709)
[docs/helpers.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/helpers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/helpers?branch=pr-en-us-13) | [Details](#user-content-dc7fd062-1e5e0709)
[docs/extensions.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/extensions?branch=pr-en-us-13) | [Details](#user-content-0fdf7c4d-1e5e0709)
[docs/troubleshooting.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/troubleshooting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/troubleshooting?branch=pr-en-us-13) | [Details](#user-content-ee7ff62f-1e5e0709)
[docs/effects.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects.md) | :white_check_mark:Succeeded | |
[docs/resources/images/managenuget.png](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/resources/images/managenuget.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) |

<a id="956af580-1e5e0709"></a>
### [docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/TOC.yml)
 - **Line 14, Column 13**: **[Warning-file-not-found]** `````Invalid file link: 'effects/safearea.md'.`````

<a id="b6b6e95c-1e5e0709"></a>
### [docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f5f9d1df-1e5e0709"></a>
### [docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'AlexHedley, sthewissen' is not a valid GitHub ID.`````
 - **Line 31, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/get-started/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="d93b521a-1e5e0709"></a>
### [docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'davidbritch, sthewissen' is not a valid GitHub ID.`````

<a id="36ca80ad-1e5e0709"></a>
### [docs/views.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/views.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c6ea3cfb-1e5e0709"></a>
### [docs/behaviors.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/behaviors.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ca2a8b71-1e5e0709"></a>
### [docs/converters.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/converters.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dc7fd062-1e5e0709"></a>
### [docs/helpers.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/helpers.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0fdf7c4d-1e5e0709"></a>
### [docs/extensions.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/extensions.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ee7ff62f-1e5e0709"></a>
### [docs/troubleshooting.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/troubleshooting.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010071415526204-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=csMw4dq61W%2F8oaMlrXr7Ttp7DqI4%2BhXVBPhhSzxKpdw%3D&st=2020-10-07T14%3A11%3A25Z&se=2020-11-07T14%3A16%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[4807537](https://github.com/sthewissen/xamarin-communitytoolkit/commits/4807537565423df4adbfc08edb5b643ec5387436)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) | [Details](#user-content-b6b6e95c-1b824d8c)
[docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) | [Details](#user-content-f5f9d1df-1b824d8c)
[docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-13) | [Details](#user-content-d93b521a-1b824d8c)
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) |
[docs/effects.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects.md) | :white_check_mark:Succeeded | |
[docs/resources/images/managenuget.png](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/resources/images/managenuget.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) |

<a id="b6b6e95c-1b824d8c"></a>
### [docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f5f9d1df-1b824d8c"></a>
### [docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'AlexHedley, sthewissen' is not a valid GitHub ID.`````
 - **Line 31, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/get-started/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="d93b521a-1b824d8c"></a>
### [docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md)
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=master)]** `````Invalid value for author: 'davidbritch, sthewissen' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010071559441911-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vrw04YFs5zbU59%2F2I8bva7dFe1vl3slrqGyzxCqm3BY%3D&st=2020-10-07T15%3A55%3A17Z&se=2020-11-07T16%3A00%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[20d3056](https://github.com/sthewissen/xamarin-communitytoolkit/commits/20d3056266fea3ddc53afd05e41a3722a2e0c3da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) | [Details](#user-content-b6b6e95c-f5c3e17a)
[docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) | [Details](#user-content-f5f9d1df-f5c3e17a)
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) |
[docs/effects.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects.md) | :white_check_mark:Succeeded | |
[docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-13) |
[docs/resources/images/managenuget.png](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/resources/images/managenuget.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) |

<a id="b6b6e95c-f5c3e17a"></a>
### [docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f5f9d1df-f5c3e17a"></a>
### [docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=master)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 31, Column 0**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=master)]** `````Link 'https://docs.microsoft.com/en-us/xamarin/get-started/' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010071638232740-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XYSYB37aO858%2B0%2BmT53zb2MmsLIRhiC4j30Fnqlxmik%3D&st=2020-10-07T16%3A33%3A55Z&se=2020-11-07T16%3A38%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sthewissen** [comment]
Since I'm the kind of guy that "OCD has to get rid of warnings" I wonder what the approach is to get rid of these last few. Obviously, I could put in a Microsoft username like @jfversluis (since he's the main MS contact for the Toolkit) or @davidbritch, OR I could come work for MS, but I'm not quite sure what the best approach for that warning is. Does it matter somewhere under the hood or where's it used? Regarding the localization one, I could link to the non-localized version but that would still be a hard link to something that might change. Is there a safer way to permalink to something else on the docs?

**Comment by davidbritch** [comment]
@sthewissen 

Whenever a new issue is opened on a doc, it gets emailed to the `ms.author`. So I'd recommend putting Gerald.

It's common to remove locale codes from links because that way the site will load the correct locale for where the user is based. In addition, it's now a requirement that we don't use https://docs.microsoft.com in links, as this stops links working in air-gapped environments, and isn't a great experience in offline books. The correct approach is to use a site-relative link. This is simply that part of the URL that comes after the locale code. So https://docs.microsoft.com/en-us/xamarin/get-started/ will become /xamarin/get-started/

**Comment by cmcclister** [comment]
Docs Build status updates of commit _[cf59de1](https://github.com/sthewissen/xamarin-communitytoolkit/commits/cf59de146ced9a691dc0e974c86a641369095cac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) |
[docs/effects.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects.md) | :white_check_mark:Succeeded | |
[docs/effects/safeareaeffect.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/effects/safeareaeffect.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/effects/safeareaeffect?branch=pr-en-us-13) |
[docs/get-started.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/get-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) |
[docs/index.md](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/index?branch=pr-en-us-13) |
[docs/resources/images/managenuget.png](https://github.com/sthewissen/xamarin-communitytoolkit/blob/master/docs/resources/images/managenuget.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/communitytoolkit/get-started?branch=pr-en-us-13) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C7%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202010071753275336-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O1TtrVGeJkkKHkOq%2Fvkz3dSU1Uwy7cE5UrERD0C0xuU%3D&st=2020-10-07T17%3A49%3A01Z&se=2020-11-07T17%3A54%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
