### PR TITLE
Add documentation for new EnumToBoolConverter

### PR DESCRIPTION
**Pull request by WebDucer**
## What changes to the docs does this PR provide?

New page for the EnumToBoolConverter with usage examples.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [ ] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by jfversluis** [comment]
Thanks @WebDucer ! There is an issue with the CI for checking if everything is OK so it might take some time before that is back up and we can actually merge it, but appreciate the effort! We will get back to you ASAP :)

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[8a58807](https://github.com/WebDucer/xamarin-communitytoolkit/commits/8a58807cd67545d5341a68d942d3c50722aebfa1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtoboolcenverter.md](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/converters/enumtoboolcenverter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolcenverter?branch=pr-en-us-91) | [Details](#user-content-0f21ac5f-089b4f7d)

<a id="0f21ac5f-089b4f7d"></a>
### [docs/converters/enumtoboolcenverter.md](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/converters/enumtoboolcenverter.md)
 - **Line 6, Column 10**: **[Warning-[ms-date-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Invalid date format for 'ms.date': '17/02/2021'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````
 - **Line 9, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Xamarin Community Toolkit IndexToArrayItemConverter' is duplicated with other articles: 'converters/enumtoboolcenverter.md(9,1), converters/indextoarrayitemconverter.md(9,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103031952502143-91%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y%2BsXxedvsUFZJUP%2FFmA2ND7h%2BknOoM57Zsu9JWQjpww%3D&st=2021-03-03T19%3A48%3A29Z&se=2021-04-03T19%3A53%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[841023d](https://github.com/WebDucer/xamarin-communitytoolkit/commits/841023dac73e42483d87d3fe9c6ee6fc1e452609)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/converters/enumtoboolcenverter.md](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/converters/enumtoboolcenverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolcenverter?branch=pr-en-us-91) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041624576735-91%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SkA37kadw6lxgCdrDsVdjiIjKffRd5dEguQMNCcmZ10%3D&st=2021-03-04T16%3A20%3A37Z&se=2021-04-04T16%3A25%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[9724dbe](https://github.com/WebDucer/xamarin-communitytoolkit/commits/9724dbede721cb873f0d1b5acb78f41132db3e14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolconverter?branch=pr-en-us-91) |
[docs/converters/enumtoboolconverter.md](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/converters/enumtoboolconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolconverter?branch=pr-en-us-91) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041626247599-91%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jD%2B1oOXYh8oWKv%2FCLHCxQcKVuRdFws1xjEPdenHHMAk%3D&st=2021-03-04T16%3A22%3A07Z&se=2021-04-04T16%3A27%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by davidbritch — APPROVED** [review]
Thanks @WebDucer

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[8490566](https://github.com/WebDucer/xamarin-communitytoolkit/commits/8490566907b3427ef96b0c00439426aaa1f945bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolconverter?branch=pr-en-us-91) |
[docs/converters/enumtoboolconverter.md](https://github.com/WebDucer/xamarin-communitytoolkit/blob/feature/enum_to_bool_converter/docs/converters/enumtoboolconverter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/converters/enumtoboolconverter?branch=pr-en-us-91) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103110913282772-91%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gT9hE4b%2Fw%2B1oHsyGpgSVtUcLqmBIfP9aFmUq4l92oZs%3D&st=2021-03-11T09%3A09%3A06Z&se=2021-04-11T09%3A14%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
