### PR TITLE
Add LocalizationResourceManager Documentation

### LINKED ISSUE #83: Add LocalizationManager Documentation
@maxkoshevoi please add the documentation for [`LocalizationResourceManager`](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/src/CommunityToolkit/Xamarin.CommunityToolkit/Helpers/LocalizationResourceManager.shared.cs)

### PR DESCRIPTION
**Pull request by davidbritch**
Original PR: https://github.com/MicrosoftDocs/xamarin-communitytoolkit/pull/86

## What changes to the docs does this PR provide?

Added new page

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] For new pages, used the [provided template](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/.template.md).
- [x] For new features, added an entry in the [Table of Contents](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/TOC.yml).
- [x] Ran against a spell and grammar checker.
- [x] Contains **NO** breaking changes.

### CODE REVIEW

**Comment by davidbritch** [comment]
Docs Build status updates of commit _[ba4c341](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/commits/ba4c34183bca2394b04145ebc72319a1407f0c5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/TOC.yml](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/dabritch-localizationmanager/docs/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-97) |
[docs/extensions/translateextension.md](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/dabritch-localizationmanager/docs/extensions/translateextension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/extensions/translateextension?branch=pr-en-us-97) |
[docs/helpers/localizationresourcemanager.md](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/dabritch-localizationmanager/docs/helpers/localizationresourcemanager.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/xamarin/community-toolkit/helpers/localizationresourcemanager?branch=pr-en-us-97) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C52490272-7c0a-c2c6-3ec7-0fb104146cb5%5CPullRequest%5C202103041553185660-97%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zAvjQqgm73nTo%2BLgkP33V4mmdXQSuzlSso%2FH8UduLtw%3D&st=2021-03-04T15%3A48%3A56Z&se=2021-04-04T15%3A53%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/52490272-7c0a-c2c6-3ec7-0fb104146cb5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by maxkoshevoi** [comment]
@davidbritch Hi, new version of this class is released, and I wanted to update the doc, but I don't have permissions to commit to `dabritch-localizationmanager` branch. Do I need to create a PR into this branch to add my changes?

Also could you please tell, what's blocking this PR?

**Comment by jfversluis** [comment]
> Also could you please tell, what's blocking this PR?

David already merged the original pr (#86) and noticed afterwards that I put on the do-not-merge tag because we were still discussing the API. He reverted the change and opened a new PR with the changes. That's why.

You can make a new PR with the changes based on this one if you want and we can then merge yours instead of this one.

**Comment by maxkoshevoi** [comment]
> You can make a new PR with the changes based on this one if you want and we can then merge yours instead of this one.

Created new PR #105

**Pull request closed without merging**
